@php $record = $record ?? null; @endphp
<section class="rounded-bucha border border-slate-200 bg-white p-6 shadow-sm space-y-4">
    <div class="grid gap-4 sm:grid-cols-2">
        @include('farmer.health.partials.animal-select', ['animals' => $animals, 'selectedAnimalId' => $selectedAnimalId ?? $record?->animal_id, 'disabled' => $record !== null])
        <div><x-input-label for="disease_name" :value="__('Disease name')" /><x-text-input id="disease_name" name="disease_name" class="mt-1 block w-full" :value="old('disease_name', $record?->disease_name)" required /></div>
        <div><x-input-label for="diagnosis_date" :value="__('Diagnosis date')" /><x-text-input id="diagnosis_date" name="diagnosis_date" type="date" class="mt-1 block w-full" :value="old('diagnosis_date', $record?->diagnosis_date?->format('Y-m-d'))" max="{{ date('Y-m-d') }}" required /></div>
        <div><x-input-label for="severity_level" :value="__('Severity')" /><select id="severity_level" name="severity_level" class="mt-1 block w-full rounded-lg border-gray-300" required>@foreach (\App\Models\DiseaseRecord::SEVERITY_LEVELS as $level)<option value="{{ $level }}" @selected(old('severity_level', $record?->severity_level) === $level)>{{ __(ucfirst($level)) }}</option>@endforeach</select></div>
        <div><x-input-label for="recovery_status" :value="__('Recovery status')" /><select id="recovery_status" name="recovery_status" class="mt-1 block w-full rounded-lg border-gray-300" required>@foreach (\App\Models\DiseaseRecord::RECOVERY_STATUSES as $status)<option value="{{ $status }}" @selected(old('recovery_status', $record?->recovery_status) === $status)>{{ __(ucfirst($status)) }}</option>@endforeach</select></div>
        <div><x-input-label for="contagious_status" :value="__('Contagious status')" /><select id="contagious_status" name="contagious_status" class="mt-1 block w-full rounded-lg border-gray-300" required>@foreach (\App\Models\DiseaseRecord::CONTAGIOUS_STATUSES as $status)<option value="{{ $status }}" @selected(old('contagious_status', $record?->contagious_status) === $status)>{{ __(ucfirst(str_replace('_', ' ', $status))) }}</option>@endforeach</select></div>
        <div class="flex items-center gap-2 pt-7"><input id="quarantine_required" name="quarantine_required" type="checkbox" value="1" @checked(old('quarantine_required', $record?->quarantine_required)) class="rounded border-gray-300"><label for="quarantine_required" class="text-sm text-slate-700">{{ __('Quarantine required') }}</label></div>
        <div class="sm:col-span-2"><x-input-label for="symptoms" :value="__('Symptoms')" /><textarea id="symptoms" name="symptoms" rows="3" class="mt-1 block w-full rounded-lg border-gray-300 text-sm">{{ old('symptoms', $record?->symptoms) }}</textarea></div>
        <div><x-input-label for="veterinarian_name" :value="__('Veterinarian name')" /><x-text-input id="veterinarian_name" name="veterinarian_name" class="mt-1 block w-full" :value="old('veterinarian_name', $record?->veterinarian_name)" /></div>
        <div class="sm:col-span-2"><x-input-label for="notes" :value="__('Notes')" /><textarea id="notes" name="notes" rows="3" class="mt-1 block w-full rounded-lg border-gray-300 text-sm">{{ old('notes', $record?->notes) }}</textarea></div>
        <div class="sm:col-span-2"><x-input-label for="attachment" :value="__('Attachment')" /><input id="attachment" name="attachment" type="file" accept=".pdf,image/*" class="mt-1 block w-full text-sm text-slate-600"></div>
    </div>
</section>
