<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Transport traceability report') }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; }
        h1 { font-size: 20px; }
        h2 { font-size: 14px; margin-top: 20px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
        .cover { margin-bottom: 24px; }
        .trip { page-break-inside: avoid; margin-bottom: 18px; padding: 12px; border: 1px solid #e2e8f0; }
        .muted { color: #64748b; }
        ul { margin: 6px 0 0 18px; padding: 0; }
    </style>
</head>
<body>
    <div class="cover">
        <h1>{{ __('Chain of custody — transport traceability') }}</h1>
        <p><strong>{{ __('Business') }}:</strong> {{ $business?->business_name ?? '—' }}</p>
        <p><strong>{{ __('Generated at') }}:</strong> {{ $generatedAt->format('d M Y H:i') }}</p>
        <p><strong>{{ __('Generated by') }}:</strong> {{ $generatedBy }}</p>
        <p><strong>{{ __('Total trips') }}:</strong> {{ $trips->count() }}</p>
        @if ($statusBreakdown->isNotEmpty())
            <p><strong>{{ __('By status') }}:</strong>
                @foreach ($statusBreakdown as $status => $count)
                    {{ ucfirst(str_replace('_', ' ', $status)) }} ({{ $count }})@if (! $loop->last), @endif
                @endforeach
            </p>
        @endif
    </div>

    @foreach ($trips as $trip)
        <div class="trip">
            <h2>{{ __('Trip') }} #{{ $trip->id }} — {{ $trip->vehicle_plate_number }} — {{ ucfirst(str_replace('_', ' ', $trip->status)) }}</h2>
            <p><strong>{{ __('Certificate') }}:</strong> {{ $trip->certificate?->certificate_number ?? '—' }}
                @if ($trip->certificate?->issued_at) ({{ __('issued') }} {{ $trip->certificate->issued_at->format('d M Y') }}) @endif
            </p>
            @if ($trip->batch)
                <p><strong>{{ __('Batch') }}:</strong> {{ $trip->batch->batch_code }}</p>
            @endif
            <p><strong>{{ __('Route') }}:</strong> {{ $trip->originFacility?->facility_name }} → {{ $trip->destination_display }}</p>
            <p><strong>{{ __('Driver') }}:</strong> {{ $trip->driver_name }} @if($trip->driver_phone)| {{ $trip->driver_phone }}@endif</p>
            <p><strong>{{ __('Departed') }}:</strong> {{ $trip->departure_date?->format('d M Y') }}
                <strong>{{ __('Arrived') }}:</strong> {{ $trip->arrival_date?->format('d M Y') ?? '—' }}</p>

            @if ($trip->deliveryConfirmation)
                @php $dc = $trip->deliveryConfirmation; @endphp
                <p class="muted" style="margin-top:8px;"><strong>{{ __('Delivery confirmation') }}</strong></p>
                <ul>
                    <li>{{ __('Status') }}: {{ ucfirst($dc->confirmation_status) }}</li>
                    <li>{{ __('Received') }}: {{ $dc->received_quantity }} {{ $dc->received_unit }} {{ __('on') }} {{ $dc->received_date->format('d M Y') }}</li>
                    <li>{{ __('Receiver') }}:
                        @if ($dc->isExternalRecipient())
                            {{ __('External') }}: {{ $dc->receiver_name }}@if($dc->receiver_country), {{ $dc->receiver_country }}@endif
                            @if($dc->receiver_address)— {{ $dc->receiver_address }}@endif
                        @else
                            {{ $dc->receivingFacility?->facility_name ?? $dc->receiver_name }}
                        @endif
                    </li>
                    @if ($dc->client)<li>{{ __('Client') }}: {{ $dc->client->display_name }}</li>@endif
                    @if ($dc->contract)<li>{{ __('Contract') }}: {{ $dc->contract->contract_number }} — {{ $dc->contract->title }}</li>@endif
                    @if ($dc->fulfillingDemand)<li>{{ __('Demand fulfilled') }}: #{{ $dc->fulfillingDemand->id }} {{ $dc->fulfillingDemand->demand_number }}</li>@endif
                </ul>
                @if ($dc->isInternationalExport())
                    <p class="muted" style="margin-top:8px;"><strong>{{ __('International export documents') }}</strong></p>
                    <ul>
                        @foreach (\App\Enums\MeatExportDocumentType::cases() as $docType)
                            @php $doc = $dc->exportDocuments->firstWhere('document_type', $docType->value); @endphp
                            <li>{{ $docType->label() }}:
                                @if ($doc)
                                    {{ $doc->document_number ?? '—' }} — {{ $doc->issuing_authority ?? '—' }} — {{ __('issued') }} {{ $doc->issued_date?->format('d M Y') ?? '—' }} — {{ ucfirst($doc->status) }}
                                @else
                                    {{ __('Not recorded') }} — {{ __('pending') }}
                                @endif
                            </li>
                        @endforeach
                    </ul>
                    @if ($dc->allExportDocumentsIssued())
                        <p><strong>✓</strong> {{ __('All required export documents are issued.') }}</p>
                    @else
                        @php
                            $missing = array_diff(
                                \App\Enums\MeatExportDocumentType::REQUIRED_TYPES,
                                $dc->exportDocuments->where('status', 'issued')->pluck('document_type')->all()
                            );
                        @endphp
                        <p><strong>⚠ {{ __('Missing documents') }}:</strong>
                            @foreach ($missing as $type)
                                {{ \App\Enums\MeatExportDocumentType::labelFor($type) }}@if (! $loop->last), @endif
                            @endforeach
                        </p>
                    @endif
                @endif
            @else
                <p class="muted">{{ __('No delivery confirmation recorded.') }}</p>
            @endif
        </div>
    @endforeach
</body>
</html>
