<section class="rounded-bucha border border-slate-200 bg-white p-6 shadow-sm space-y-4" x-data="{ target: '{{ old('target_type', 'animal') }}' }">
    <div class="grid gap-4 sm:grid-cols-2">
        <div class="sm:col-span-2"><x-input-label for="target_type" :value="__('Feeding target')" /><select id="target_type" name="target_type" x-model="target" class="mt-1 block w-full rounded-lg border-gray-300" required><option value="animal">{{ __('Individual animal') }}</option><option value="livestock">{{ __('Livestock group') }}</option></select></div>
        <div x-show="target === 'animal'"><x-input-label for="animal_id" :value="__('Animal')" /><select id="animal_id" name="animal_id" class="mt-1 block w-full rounded-lg border-gray-300"><option value="">{{ __('Select animal') }}</option>@foreach ($animals as $animal)<option value="{{ $animal->id }}" @selected((int) old('animal_id') === $animal->id)>{{ $animal->selectionLabel() }}</option>@endforeach</select></div>
        <div x-show="target === 'livestock'"><x-input-label for="livestock_id" :value="__('Livestock group')" /><select id="livestock_id" name="livestock_id" class="mt-1 block w-full rounded-lg border-gray-300"><option value="">{{ __('Select group') }}</option>@foreach ($livestock as $group)<option value="{{ $group->id }}" @selected((int) old('livestock_id') === $group->id)>{{ $group->livestock_name }}</option>@endforeach</select></div>
        <div><x-input-label for="feed_type_id" :value="__('Feed type')" /><select id="feed_type_id" name="feed_type_id" class="mt-1 block w-full rounded-lg border-gray-300" required><option value="">{{ __('Select feed type') }}</option>@foreach ($feedTypes as $feedType)<option value="{{ $feedType->id }}" @selected((int) old('feed_type_id') === $feedType->id)>{{ $feedType->feed_name }}</option>@endforeach</select></div>
        <div><x-input-label for="feed_inventory_id" :value="__('Inventory batch')" /><select id="feed_inventory_id" name="feed_inventory_id" class="mt-1 block w-full rounded-lg border-gray-300" required><option value="">{{ __('Select batch') }}</option>@foreach ($inventories as $inventory)<option value="{{ $inventory->id }}" @selected((int) old('feed_inventory_id') === $inventory->id)>{{ $inventory->inventory_code }} · {{ number_format((float) $inventory->quantity_remaining, 2) }}</option>@endforeach</select></div>
        <div><x-input-label for="quantity" :value="__('Quantity')" /><x-text-input id="quantity" name="quantity" type="number" step="0.001" min="0.001" class="mt-1 block w-full" :value="old('quantity')" required /></div>
        <div><x-input-label for="feeding_date" :value="__('Feeding date')" /><x-text-input id="feeding_date" name="feeding_date" type="date" class="mt-1 block w-full" :value="old('feeding_date', date('Y-m-d'))" max="{{ date('Y-m-d') }}" required /></div>
        <div><x-input-label for="feeding_time" :value="__('Feeding time')" /><x-text-input id="feeding_time" name="feeding_time" type="time" class="mt-1 block w-full" :value="old('feeding_time')" /></div>
        <div><x-input-label for="feeding_method" :value="__('Method')" /><select id="feeding_method" name="feeding_method" class="mt-1 block w-full rounded-lg border-gray-300"><option value="">{{ __('Optional') }}</option>@foreach (\App\Models\FeedingRecord::METHODS as $method)<option value="{{ $method }}" @selected(old('feeding_method') === $method)>{{ __(ucwords(str_replace('_', ' ', $method))) }}</option>@endforeach</select></div>
        <div><x-input-label for="appetite_status" :value="__('Appetite')" /><select id="appetite_status" name="appetite_status" class="mt-1 block w-full rounded-lg border-gray-300"><option value="">{{ __('Optional') }}</option>@foreach (\App\Models\FeedingRecord::APPETITE_STATUSES as $status)<option value="{{ $status }}" @selected(old('appetite_status') === $status)>{{ __(ucwords(str_replace('_', ' ', $status))) }}</option>@endforeach</select></div>
        <div class="flex items-center gap-2 pt-7"><input id="water_provided" name="water_provided" type="checkbox" value="1" @checked(old('water_provided')) class="rounded border-gray-300"><label for="water_provided" class="text-sm text-slate-700">{{ __('Water provided') }}</label></div>
        <div class="sm:col-span-2"><x-input-label for="notes" :value="__('Notes')" /><textarea id="notes" name="notes" rows="3" class="mt-1 block w-full rounded-lg border-gray-300 text-sm">{{ old('notes') }}</textarea></div>
    </div>
</section>
