<section class="rounded-bucha border border-slate-200 bg-white p-6 shadow-sm space-y-4" x-data="{ target: '{{ old('target_type', 'livestock') }}' }">
    <div class="grid gap-4 sm:grid-cols-2">
        <div><x-input-label for="business_id" :value="__('Business')" /><select id="business_id" name="business_id" class="mt-1 block w-full rounded-lg border-gray-300" required>@foreach ($businesses as $businessId)<option value="{{ $businessId }}">#{{ $businessId }}</option>@endforeach</select></div>
        <div><x-input-label for="schedule_name" :value="__('Schedule name')" /><x-text-input id="schedule_name" name="schedule_name" class="mt-1 block w-full" :value="old('schedule_name')" required /></div>
        <div class="sm:col-span-2"><x-input-label for="target_type" :value="__('Target')" /><select id="target_type" name="target_type" x-model="target" class="mt-1 block w-full rounded-lg border-gray-300" required><option value="animal">{{ __('Individual animal') }}</option><option value="livestock">{{ __('Livestock group') }}</option></select></div>
        <div x-show="target === 'animal'"><x-input-label for="animal_id" :value="__('Animal')" /><select id="animal_id" name="animal_id" class="mt-1 block w-full rounded-lg border-gray-300"><option value="">{{ __('Select animal') }}</option>@foreach ($animals as $animal)<option value="{{ $animal->id }}">{{ $animal->selectionLabel() }}</option>@endforeach</select></div>
        <div x-show="target === 'livestock'"><x-input-label for="livestock_id" :value="__('Livestock group')" /><select id="livestock_id" name="livestock_id" class="mt-1 block w-full rounded-lg border-gray-300"><option value="">{{ __('Select group') }}</option>@foreach ($livestock as $group)<option value="{{ $group->id }}">{{ $group->livestock_name }}</option>@endforeach</select></div>
        <div><x-input-label for="feed_type_id" :value="__('Feed type')" /><select id="feed_type_id" name="feed_type_id" class="mt-1 block w-full rounded-lg border-gray-300" required>@foreach ($feedTypes as $feedType)<option value="{{ $feedType->id }}">{{ $feedType->feed_name }}</option>@endforeach</select></div>
        <div><x-input-label for="feeding_time" :value="__('Feeding time')" /><x-text-input id="feeding_time" name="feeding_time" type="time" class="mt-1 block w-full" :value="old('feeding_time')" required /></div>
        <div><x-input-label for="feeding_frequency" :value="__('Frequency')" /><select id="feeding_frequency" name="feeding_frequency" class="mt-1 block w-full rounded-lg border-gray-300" required>@foreach (\App\Models\FeedingSchedule::FREQUENCIES as $frequency)<option value="{{ $frequency }}">{{ __(ucwords(str_replace('_', ' ', $frequency))) }}</option>@endforeach</select></div>
        <div><x-input-label for="quantity" :value="__('Quantity')" /><x-text-input id="quantity" name="quantity" type="number" step="0.001" min="0.001" class="mt-1 block w-full" :value="old('quantity')" required /></div>
        <div><x-input-label for="status" :value="__('Status')" /><select id="status" name="status" class="mt-1 block w-full rounded-lg border-gray-300" required>@foreach (\App\Models\FeedingSchedule::STATUSES as $status)<option value="{{ $status }}">{{ __(ucfirst($status)) }}</option>@endforeach</select></div>
        <div class="sm:col-span-2"><x-input-label for="instructions" :value="__('Instructions')" /><textarea id="instructions" name="instructions" rows="3" class="mt-1 block w-full rounded-lg border-gray-300 text-sm">{{ old('instructions') }}</textarea></div>
    </div>
</section>
